server:
  port: 8090

kafka:
  producer:
    bootStrapServer: localhost:9092
#below properties are supported by framework and need not to create producer factory if defined.
spring:
  cloud:
    stream:
      kafka:
        binder:
          autoCreateTopics: false
  kafka:
    auto:
      create:
        topics:
          enable: false
    bootstrap-servers: "localhost:9092"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      group-id: group_id